name: '${project.name}'
version: 'MC${plugin.minecraft}: ${project.version}-${git.commit.id.abbrev}'
description: '${project.description}'
authors:
- grzegorz2047
website: 'https://github.com/grzegorz2047/PseudoHC'
main: '${plugin.main}'
