name: PseudoHC
version: 0.0.1
main: com.gmail.grzegorz2047.pseudohc.PseudoHC
commands:
    guild:
        description: Commands related to guilds
        aliases: [g, gildia, guild, clan, f]
        usage: /guild <arg[s]...> Type 'guild help' for help